import Link from "next/link";
import { LEGAL } from "@/lib/legal";

// Site footer. A paid product needs a visible owner: a way to reach support,
// and the legal pages. Rendered on every route from the root layout, below
// <main>, which is why layout.tsx keeps the body as a flex column.

const linkClass = "transition-opacity hover:opacity-70";

export function Footer() {
  return (
    <footer className="mt-16 border-t border-primary/8 bg-white/60">
      <div className="w-full px-4 md:px-10 xl:px-16 2xl:px-24 py-8">
        <div className="flex flex-col gap-6 md:flex-row md:items-start md:justify-between">
          <div>
            <p className="font-headline text-lg font-bold tracking-tight text-primary">
              Elovox
            </p>
            <p className="mt-1 text-sm text-on-surface-variant">
              Speak with impact.
            </p>
          </div>

          <nav
            aria-label="Footer"
            className="flex flex-col gap-2 text-sm text-on-surface-variant sm:flex-row sm:gap-6"
          >
            <Link href="/pricing" className={linkClass}>
              Pricing
            </Link>
            <Link href="/terms" className={linkClass}>
              Terms
            </Link>
            <Link href="/privacy" className={linkClass}>
              Privacy
            </Link>
            <a href={`mailto:${LEGAL.contactEmail}`} className={linkClass}>
              Contact
            </a>
            <a
              href={LEGAL.instagramUrl}
              target="_blank"
              rel="noopener noreferrer"
              className={linkClass}
            >
              Instagram
            </a>
          </nav>
        </div>

        <p className="mt-8 text-xs text-on-surface-variant">
          © {new Date().getFullYear()} {LEGAL.serviceName}. Coaching feedback is
          generated by AI and can be wrong — treat it as practice, not advice.
        </p>
      </div>
    </footer>
  );
}
