import Link from "next/link";
import { LEGAL } from "@/lib/legal";
import { FooterAboutLink } from "@/components/FooterAboutLink";

// Site footer. A paid product needs a visible owner: a way to reach support,
// and the legal pages. Rendered on every route from the root layout, below
// <main>, which is why layout.tsx keeps the body as a flex column.

// `py-2 -my-2` grows the tap target to 36px without changing the layout:
// stacked on mobile these were 20px-tall links 8px apart, well under the 44px
// WCAG 2.5.8 target and genuinely fiddly to hit with a thumb.
//
// The gap below it is part of this and must stay at least TWICE the padding.
// It was `gap-2` — 8px — against 8px of padding, so every link's grown box
// reached 8px into its neighbour's and the two overlapped by exactly that.
// Measured with elementFromPoint: a tap in the shared band opened the LOWER
// link every time, so the bottom 8px of "Terms" was really "Privacy" and the
// growth meant to make these easier to hit had quietly made a quarter of each
// one wrong. At `gap-4` the boxes meet without crossing: every pixel belongs
// to exactly one link.
const linkClass = "py-2 -my-2 transition-opacity hover:opacity-70";

// The footer owns the gap above itself. Every page used to add its own trailing
// pb-20/pb-24 on top of this margin, so the bottom of the site carried 144-160px
// of stacked dead space and read as a rendering fault rather than as spacing.
// One owner, one token. Pages must NOT add bottom padding — there is a test.
export function Footer() {
  return (
    <footer className="mt-[var(--space-section)] border-t border-primary/8 bg-surface-warm/70">
      <div className="w-full px-4 md:px-10 xl:px-16 2xl:px-24 py-8">
        <div className="flex flex-col gap-6 md:flex-row md:items-start md:justify-between">
          <div>
            <p className="font-headline text-lg font-bold tracking-tight text-primary">
              Elovox
            </p>
            <p className="mt-1 text-sm text-on-surface-variant">
              Speak with impact.
            </p>
          </div>

          {/* sm:flex-wrap since Accessibility made this seven items: on a
              narrow tablet the row overran the footer's right edge rather than
              wrapping, which pushed Instagram off the page. */}
          <nav
            aria-label="Footer"
            className="flex flex-col gap-4 text-sm text-on-surface-variant sm:flex-row sm:flex-wrap sm:gap-x-6 sm:gap-y-4"
          >
            <FooterAboutLink className={linkClass} />
            <Link href="/pricing" className={`${linkClass} web-only`}>
              Pricing
            </Link>
            <Link href="/terms" className={linkClass}>
              Terms
            </Link>
            <Link href="/privacy" className={linkClass}>
              Privacy
            </Link>
            <Link href="/refunds" className={linkClass}>
              Refunds
            </Link>
            <Link href="/accessibility" className={linkClass}>
              Accessibility
            </Link>
            <Link href="/legal" className={linkClass}>
              Legal
            </Link>
            <a href={`mailto:${LEGAL.emails.support}`} className={linkClass}>
              Contact
            </a>
            <a
              href={LEGAL.instagramUrl}
              target="_blank"
              rel="noopener noreferrer"
              className={linkClass}
            >
              Instagram
            </a>
          </nav>
        </div>

        <p className="mt-8 text-xs text-on-surface-variant">
          © {new Date().getFullYear()} {LEGAL.serviceName}. Coaching feedback is
          generated by AI and can be wrong, treat it as practice, not advice.
        </p>
      </div>
    </footer>
  );
}
