"use client";

import Link from "next/link";
import { useTheme, useIsNative, type Theme } from "@/lib/native";
import { LEGAL } from "@/lib/legal";

/**
 * The two things Account has to absorb once the app stops being a website:
 * the appearance choice (dark mode is native-only) and the legal links the
 * footer used to carry. iOS users look for both here and nowhere else.
 *
 * Renders nothing in a browser — the web keeps its footer.
 */

/* Each option is its own miniature of the app: bar, card, record node. Picking
   a theme from two words is a guess; picking it from two pictures isn't. */
function ThemeSwatch({ theme }: { theme: Theme }) {
  const dark = theme === "dark";
  return (
    <span
      aria-hidden="true"
      className="block h-16 w-full overflow-hidden rounded-lg border"
      style={{
        background: dark ? "#0d0a20" : "#f4f7fc",
        borderColor: dark ? "rgba(203,216,255,0.16)" : "rgba(0,78,137,0.14)",
      }}
    >
      <span
        className="mt-2.5 ml-2.5 block h-1.5 w-10 rounded-full"
        style={{ background: dark ? "#cbd8ff" : "#004e89" }}
      />
      <span
        className="mt-2 ml-2.5 block h-6 w-[70%] rounded-md"
        style={{
          background: dark ? "#171331" : "#ffffff",
          border: `1px solid ${dark ? "rgba(203,216,255,0.12)" : "rgba(0,78,137,0.13)"}`,
        }}
      />
      <span
        className="-mt-4 ml-auto mr-2.5 block h-5 w-5 rounded-full"
        style={{ background: "#ff6b35" }}
      />
    </span>
  );
}

function AppearanceCard() {
  const [theme, setThemeState] = useTheme();

  const option = (value: Theme, label: string) => {
    const selected = theme === value;
    return (
      <button
        key={value}
        type="button"
        onClick={() => setThemeState(value)}
        aria-pressed={selected}
        className={`flex-1 rounded-xl border p-2 text-left transition-colors ${
          selected
            ? "border-accent bg-accent/8"
            : "border-outline-variant/60 bg-transparent"
        }`}
      >
        <ThemeSwatch theme={value} />
        <span className="mt-2 flex items-center gap-1.5 px-0.5 text-[13px] font-semibold text-primary">
          {label}
          {selected && <span className="text-accent">✓</span>}
        </span>
      </button>
    );
  };

  return (
    <section className="card p-5">
      <h2 className="font-headline text-lg font-semibold text-primary">
        Appearance
      </h2>
      <p className="mt-1 text-sm text-on-surface-variant">
        Dark is easier on the eyes when you practise at night.
      </p>
      <div className="mt-4 flex gap-3">
        {option("light", "Light")}
        {option("dark", "Dark")}
      </div>
    </section>
  );
}

/* A grouped list, the way settings are grouped on iOS: hairline separators
   inside one card, chevrons on anything that navigates. */
function Row({
  href,
  external,
  children,
}: {
  href: string;
  external?: boolean;
  children: React.ReactNode;
}) {
  const inner = (
    <>
      <span className="text-base text-on-surface">{children}</span>
      <svg
        width="18"
        height="18"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
        className="text-on-surface-variant/60"
      >
        <path d="m9.5 5 7 7-7 7" />
      </svg>
    </>
  );
  const className =
    "flex items-center justify-between px-5 py-3.5 border-t border-outline-variant/40 first:border-t-0 active:bg-surface-container/60 transition-colors";

  if (external) {
    return (
      <a
        href={href}
        target="_blank"
        rel="noopener noreferrer"
        className={className}
      >
        {inner}
      </a>
    );
  }
  return (
    <Link href={href} className={className}>
      {inner}
    </Link>
  );
}

export function NativeAccountSection() {
  const native = useIsNative();
  if (!native) return null;

  return (
    <>
      <AppearanceCard />

      <section className="card overflow-hidden">
        <h2 className="px-5 pt-5 pb-3 font-headline text-lg font-semibold text-primary">
          About Elovox
        </h2>
        <Row href="/about">Who makes this</Row>
        <Row href={`mailto:${LEGAL.contactEmail}`} external>
          Contact support
        </Row>
        <Row href={LEGAL.instagramUrl} external>
          Instagram
        </Row>
        <Row href="/terms">Terms of service</Row>
        <Row href="/privacy">Privacy policy</Row>
      </section>

      <p className="px-1 text-center text-xs leading-5 text-on-surface-variant">
        © {new Date().getFullYear()} {LEGAL.serviceName}
        <br />
        Coaching feedback is generated by AI and can be wrong. Treat it as
        practice, not advice.
      </p>
    </>
  );
}
