import type { Metadata } from "next";
import Link from "next/link";
import { LegalDoc, Section, Bullets } from "@/components/LegalDoc";
import { LEGAL } from "@/lib/legal";
import { PLANS, formatUSD, hasTrial } from "@/lib/pricing";

// Terms of service. The subscription section is generated from lib/pricing
// so the prices and trial lengths quoted here can never contradict what
// checkout actually charges.

export const metadata: Metadata = {
  title: "Terms of Service — Elovox",
  description:
    "The agreement between you and Elovox: what the service does, how subscriptions and trials work, and the limits of AI coaching feedback.",
  alternates: { canonical: "/terms" },
};

const mailto = `mailto:${LEGAL.contactEmail}`;

export default function TermsPage() {
  return (
    <LegalDoc
      title="Terms of Service"
      intro={`These terms are the agreement between you and ${LEGAL.entity} for the use of Elovox. By creating an account or using the service you accept them, so it's worth the five minutes it takes to read.`}
    >
      <Section heading="What Elovox is">
        <p>
          Elovox records you speaking and returns automated feedback on your
          delivery — pace, filler words, pauses, clarity, tone, and, if you use
          the camera, your posture and expression. It is a practice tool.
        </p>
        <p>
          It is not coaching from a person, and it is not professional advice of
          any kind. It cannot tell you whether you will pass an interview, win a
          pitch, or be well received by a particular audience, and nothing it
          says should be treated as a prediction of any of those things.
        </p>
      </Section>

      <Section heading="Feedback is generated by AI, and can be wrong">
        <p>
          Your transcript and your scores come from automated systems — speech
          recognition and a large language model. Both make mistakes. The
          transcript may mishear you, and the feedback may be confidently
          inaccurate, inconsistent between attempts, or simply unhelpful.
        </p>
        <p>
          Use it as one input among many. Do not rely on it for any decision
          that matters — professional, academic, medical, financial, or legal.
          Scores are a practice aid, not an assessment of your ability or worth.
        </p>
      </Section>

      <Section heading="Your account">
        <p>
          You must be at least {LEGAL.minimumAge}{" "}
          years old to hold an account, and if you are under 18 you need a
          parent or guardian&apos;s
          permission. You are responsible for keeping your password private and
          for what happens under your account. Give us accurate information, and
          tell us promptly at{" "}
          <a className="text-accent hover:underline" href={mailto}>
            {LEGAL.contactEmail}
          </a>{" "}
          if you think someone else has access to it.
        </p>
      </Section>

      <Section heading="Free and Premium">
        <p>
          The free plan gives you the daily challenge with a limited number of
          attempts each day. Premium removes the limits and adds the speech
          library, interview practice, camera coaching, and coaching on your own
          material. Current plans:
        </p>
        <Bullets
          items={PLANS.map((p) => (
            <span key={p.cycle}>
              <strong>{p.label}</strong> — {formatUSD(p.price)} per {p.unit}
              {hasTrial(p)
                ? `, after a ${p.trialDays}-day free trial.`
                : ", charged from the day you subscribe (no free trial)."}
            </span>
          ))}
        />
        <p>
          We may change what&apos;s included in each plan, or change prices. If
          a price change affects a subscription you already hold, we&apos;ll
          tell you before it takes effect, and you can cancel if you don&apos;t
          want to continue. See the{" "}
          <Link href="/pricing" className="text-accent hover:underline">
            pricing page
          </Link>{" "}
          for what&apos;s current.
        </p>
      </Section>

      <Section heading="Trials, renewal, and cancellation">
        <p>
          The monthly and annual plans start with a free trial; the weekly plan
          does not, and is charged as soon as you subscribe.
        </p>
        <p>
          Starting a trial requires a payment method. Unless you cancel before
          the trial ends, it converts into a paid subscription automatically and
          you are charged for the first period.
        </p>
        <p>
          <strong>Subscriptions renew automatically</strong> at the end of each
          billing period, at the then-current price, until you cancel. You can
          cancel at any time from the billing page in your account, which opens
          Stripe&apos;s customer portal. Cancelling stops the next charge; your
          access continues until the end of the period you have already paid
          for.
        </p>
        <p>
          If a payment fails, we may keep your access active briefly while the
          payment is retried. If it keeps failing, the subscription ends.
        </p>
      </Section>

      <Section heading="Refunds">
        <p>
          Payments are generally non-refundable, including for periods you
          didn&apos;t use — that&apos;s what the free trial is for. If something
          went genuinely wrong, email{" "}
          <a className="text-accent hover:underline" href={mailto}>
            {LEGAL.contactEmail}
          </a>{" "}
          and we&apos;ll look at it fairly.
        </p>
        <p>
          Consumers in some places — including the UK, EU, and parts of the
          United States — have statutory refund or cancellation rights that
          these terms cannot take away. Nothing here limits those rights.
        </p>
      </Section>

      <Section heading="Your content">
        <p>
          What you record and write stays yours. You keep all rights to your
          recordings, transcripts, and anything you type into Elovox.
        </p>
        <p>
          To provide the service, you give us permission to process that content
          for one purpose only: producing your feedback and your practice
          history, including by sending it to the providers named in our{" "}
          <Link href="/privacy" className="text-accent hover:underline">
            Privacy Policy
          </Link>
          . We do not use your recordings to train our own models, we do not
          publish them, and we do not sell them. That permission ends when you
          delete the content or your account.
        </p>
        <p>
          You are responsible for what you record. Don&apos;t upload anything
          you don&apos;t have the right to use, and don&apos;t record other
          people without their consent.
        </p>
      </Section>

      <Section heading="Our content">
        <p>
          The practice material Elovox writes for you is yours to use freely for
          practice and performance. Everything else — the software, the site,
          the name, and the fox — belongs to us, and these terms don&apos;t give
          you rights to it beyond using the service normally.
        </p>
      </Section>

      <Section heading="Acceptable use">
        <p>You agree not to:</p>
        <Bullets
          items={[
            "Break the law with it, or use it to harass, defraud, or impersonate anyone.",
            "Upload someone else's voice or likeness without their permission.",
            "Attempt to bypass plan limits, quotas, or payment — including by creating multiple accounts to avoid the free-tier cap.",
            "Scrape the service, resell it, or run automated load against it.",
            "Attack the service or attempt to gain access to systems or accounts that aren't yours.",
          ]}
        />
        <p>
          We may suspend or close an account that does these things, and we may
          impose rate limits to keep the service running for everyone.
        </p>
      </Section>

      <Section heading="Availability">
        <p>
          We&apos;ll try to keep Elovox running and working well, but we
          don&apos;t promise it will always be available or error-free. Features
          may change or be removed. Parts of it depend on third-party providers,
          and their outages become ours.
        </p>
      </Section>

      <Section heading="Ending the agreement">
        <p>
          You can stop using Elovox at any time, and delete your account
          permanently from your{" "}
          <Link href="/account" className="text-accent hover:underline">
            account settings
          </Link>
          . Deleting cancels any active subscription immediately.
          We may suspend or end your access if you break these terms, or if we
          discontinue the service — in which case we&apos;ll refund any period
          you&apos;ve paid for but can no longer use.
        </p>
      </Section>

      <Section heading="Disclaimers and liability">
        <p>
          Elovox is provided &ldquo;as is&rdquo;. To the fullest extent the law
          allows, we disclaim all implied warranties, including fitness for a
          particular purpose, and we are not liable for indirect or
          consequential losses, lost opportunities, or lost profits — including
          any outcome of an interview, pitch, audition, or speech you practiced
          for.
        </p>
        <p>
          Where liability cannot be excluded, our total liability to you is
          limited to the amount you paid us in the twelve months before the
          claim. Nothing here excludes liability that cannot legally be
          excluded, and if you are a consumer you keep all your statutory
          rights.
        </p>
      </Section>

      <Section heading="Governing law">
        <p>
          These terms are governed by the laws of {LEGAL.jurisdiction}, and
          disputes will be heard by the courts there. If you are a consumer, you
          may also have the right to bring proceedings in your own country.
        </p>
      </Section>

      <Section heading="Changes to these terms">
        <p>
          We may update these terms. If a change is significant we&apos;ll tell
          you in the app or by email before it takes effect, and continuing to
          use Elovox afterwards means you accept the new version. The date at
          the top always reflects the current one.
        </p>
      </Section>

      <Section heading="Contact">
        <p>
          Questions about any of this go to{" "}
          <a className="text-accent hover:underline" href={mailto}>
            {LEGAL.contactEmail}
          </a>
          . We&apos;re also on Instagram as{" "}
          <a
            className="text-accent hover:underline"
            href={LEGAL.instagramUrl}
            target="_blank"
            rel="noopener noreferrer"
          >
            @{LEGAL.instagramHandle}
          </a>
          , though support requests are better by email.
        </p>
      </Section>
    </LegalDoc>
  );
}
