// The coarse buckets analysis scores against. Not the same list as the
// "My material" picker on /own: `job-interview` is internal, set by the
// dedicated interview-practice mode, and is deliberately absent from the
// picker (see lib/categories.ts).
export type CategoryId =
  | "job-interview"
  | "sales-pitch"
  | "prepared-speech"
  | "toast-tribute"
  | "general-coaching"
  | "conversation";

export interface Category {
  id: CategoryId;
  name: string;
  description: string;
}

export interface SkillScore {
  skill: string;
  score: number; // 0-100
  note: string;
}

export interface TranscriptSegment {
  text: string;
  mark?: "strong" | "flag";
  time?: string; // mm:ss where the moment happens
  note?: string; // coach's annotation
}

/** One scored dimension of physical delivery, from the camera pass. */
export interface StageMetric {
  metric: string;
  score: number; // 0-100
  note: string;
}

/**
 * Body-language feedback (Premium). Produced by sampling frames from the
 * video track and having Felix read them alongside the audio timeline —
 * posture, sway, gestures, expression, eye contact, and what the body was
 * doing during the pauses.
 */
export interface StageAnalysis {
  overall: number; // 0-100 physical presence
  summary: string;
  metrics: StageMetric[];
  tips: string[];
}

/** A targeted practice exercise (Premium reports only). */
export interface Drill {
  title: string;
  how: string;
}

export interface Analysis {
  isSample?: boolean; // true when generated by the placeholder, not the real pipeline
  overall: number; // 0-100, computed from the dimension scores
  summary: string;
  skills: SkillScore[]; // the scored delivery dimensions
  transcript: TranscriptSegment[];
  tips: string[];
  audienceImpact?: string; // Felix's prediction of how listeners perceived it
  strengths?: string[]; // Premium: specific things done well, worth keeping
  drills?: Drill[]; // Premium: targeted practice exercises
  stage?: StageAnalysis; // present only when the user recorded with camera on
  paceWpm: number;
  fillerWords: number;
  pauses: number;
  /**
   * Set only when language screening (lib/profanity.ts) masked words in this
   * transcript: what was hidden, and what it cost. Absent on every clean
   * recording, which is nearly all of them.
   */
  languageNotice?: string;
}

export type GoalId =
  | "trust"
  | "agree"
  | "inspire"
  | "leader"
  | "empathy"
  | "intelligent"
  | "memorable"
  | "calm";

export interface Goal {
  id: GoalId;
  label: string; // "Make people trust me"
}

/** Where a rep came from, drives how it's labeled and scored in Progress. */
export type PracticeMode =
  | "daily" // the universal 1-minute challenge
  | "library" // the ~30s Premium speech bank
  | "own" // the user's own material
  | "interview" // interview practice
  | "social" // social skills practice
  | "custom"; // a speech Felix wrote for this user

export interface Session {
  id: string;
  category: CategoryId;
  mode?: PracticeMode; // absent on sessions recorded before modes existed
  prompt: string;
  goal?: string; // goal label the speaker asked Felix to judge against
  speechId?: string; // set when practicing a library speech
  speechTitle?: string; // library/custom/daily title, or the social skill name
  challengeDate?: string; // YYYY-MM-DD, set on daily-challenge reps
  attempt?: number; // 1-3, set on daily-challenge reps
  interviewType?: InterviewTypeId;
  socialSkillId?: SocialSkillId;
  withVideo?: boolean; // camera was on (Premium)
  xpEarned?: number;
  /**
   * The itemised working behind `xpEarned`, exactly as xpForChallengeAttempt
   * returned it ("Attempt 2 · 87 score", "+42 beat your best by 9", …).
   *
   * Stored so the report can show the receipt whenever it is opened, not only
   * in the seconds after the take. Optional: absent on every rep recorded
   * before this field existed, and on non-daily reps, which have no breakdown
   * to show — a flat rate needs no itemising.
   */
  xpReasons?: string[];
  /** The level this attempt crossed into, if it crossed one. */
  leveledUpTo?: number;
  /** This attempt beat the day's previous best (or was the day's first). */
  isNewBest?: boolean;
  createdAt: number; // epoch ms
  durationSec: number;
  analysis: Analysis;
}

export type InterviewTypeId =
  | "job"
  | "college"
  | "scholarship"
  | "grad-school"
  | "internship"
  | "medical-law";

export interface InterviewType {
  id: InterviewTypeId;
  name: string;
  description: string;
  questions: string[];
}

export type SocialSkillId =
  | "small-talk"
  | "ending-conversations"
  | "excusing-yourself"
  | "boundaries"
  | "disagreeing"
  | "compliments"
  | "awkward-silence"
  | "joining-groups"
  | "apologies"
  | "declining-invitations"
  | "asking-for-help"
  | "receiving-criticism"
  | "reconnecting";

export interface SocialSkill {
  id: SocialSkillId;
  name: string;
  description: string;
  prompts: string[]; // concrete moments, spoken back to in the user's own words
}
