import type { Metadata } from "next";
import Link from "next/link";
import { LegalDoc, Section, Bullets } from "@/components/LegalDoc";
import { LEGAL } from "@/lib/legal";
import { pageGraph } from "@/lib/schema";

// How Felix works — the plain-language AI disclosure. Felix is presented as a
// character throughout the product, so this is the page that says out loud that
// the coaching is machine-generated, what it can and can't do, and which models
// see your recording. Keep it honest about the limits; an overselling AI page
// is its own liability.

const TITLE = "How Felix works | Elovox";
const DESCRIPTION =
  "Elovox's coaching is generated by AI. What that means, what it can't do, and which models see your recording.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: "/ai" },
  openGraph: {
    type: "article",
    siteName: "Elovox",
    url: "/ai",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/og.png"],
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    images: ["/og.png"],
  },
};

const mailto = `mailto:${LEGAL.emails.support}`;
const SITE = "https://elovox.app";
const modified = (() => {
  const d = new Date(LEGAL.aiUpdated);
  return Number.isNaN(d.getTime()) ? undefined : d.toISOString().slice(0, 10);
})();

const PAGE_SCHEMA = {
  "@type": "WebPage",
  "@id": `${SITE}/ai#webpage`,
  url: `${SITE}/ai`,
  name: TITLE,
  description: DESCRIPTION,
  isPartOf: { "@id": `${SITE}/#website` },
  publisher: { "@id": `${SITE}/#organization` },
  ...(modified ? { dateModified: modified } : {}),
};

export default function AiPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(pageGraph(PAGE_SCHEMA)) }}
      />
      <LegalDoc
        title="How Felix works"
        updated={LEGAL.aiUpdated}
        intro="Felix is the coach inside Elovox. Felix is not a person; it's AI. Your feedback and scores are generated automatically by machine-learning models, not written by a human listening in. That's worth understanding before you lean on any of it."
      >
        <Section heading="What actually happens to a practice run">
          <Bullets
            items={[
              "Speech-to-text turns your recording into a transcript with timings.",
              "A large language model reads that transcript plus the measured metrics (pace, fillers, pauses) and writes the coaching, the scores, and the summary.",
              "If you practiced with the camera on, a small number of still frames are also read by the model so it can comment on posture and expression.",
            ]}
          />
          <p>
            The specific providers are named in the{" "}
            <Link href="/privacy" className="text-accent-strong hover:underline">
              Privacy Policy
            </Link>
            , which also explains what is and isn&apos;t kept.
          </p>
        </Section>

        <Section heading="It can be wrong">
          <p>
            Both the transcription and the coaching make mistakes. The transcript
            can mishear you. The feedback can be confidently inaccurate,
            inconsistent between two attempts at the same thing, or just
            unhelpful. The scores are a practice aid to measure yourself against
            over time, not an objective assessment of your ability, and not a
            prediction of how a real interview, pitch, or audience will go.
          </p>
        </Section>

        <Section heading="Not professional advice">
          <p>
            Elovox is a practice tool, not a professional service. Nothing Felix
            says is professional, medical, legal, financial, or career advice.
            Don&apos;t make a decision that matters on the strength of it. Use it
            as one input, alongside people whose judgment you trust.
          </p>
        </Section>

        <Section heading="On the camera feedback">
          <p>
            When you turn the camera on, the model comments on visible delivery:
            posture, gestures, eye contact, expression. It is reading readily
            visible behavior to coach you, and it can misread you, especially if
            you move, present, or express yourself differently from whatever it
            treats as the norm. It does not identify you, and it builds no
            face template. See the{" "}
            <Link href="/biometrics" className="text-accent-strong hover:underline">
              voice &amp; camera notice
            </Link>
            . The camera is off unless you turn it on.
          </p>
        </Section>

        <Section heading="On Felix's spoken take">
          <p>
            The short take at the top of a report is written by the same model
            from the finished analysis, not from the recording, and it is held
            to about sixty words. That is a summary of a summary: it says what
            matters most, and it can leave out something the full report
            covers. The written report underneath is the complete version, and
            the take is always there as text, so nothing depends on the audio.
            His voice is generated speech; see the{" "}
            <Link href="/privacy" className="text-accent-strong hover:underline">
              privacy policy
            </Link>{" "}
            for who processes it.
          </p>
        </Section>

        <Section heading="Questions">
          <p>
            If anything about how Felix works is unclear, email{" "}
            <a className="text-accent-strong hover:underline" href={mailto}>
              {LEGAL.emails.support}
            </a>
            .
          </p>
        </Section>
      </LegalDoc>
    </>
  );
}
